name: Hello World

on:
  push:
   branches:
    - 'main'
  pull_request:
    branches:
    -  'main'

    jobs:
      tests:
       runs-on: windows-latest

       steps:
        - name: Hello Step
          run: echo "Hello World"